version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ndarite_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    restart: unless-stopped
    command: sh -c "npm install && npx next dev --hostname 0.0.0.0"

networks:
  default:
    name: ndarite_network
    external: true
